# Generated by Django 4.2.16 on 2024-12-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_car_mileage_alter_car_location_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='green', max_length=50),
            preserve_default=False,
        ),
    ]
