# Generated by Django 4.2.16 on 2024-12-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='location',
            new_name='zipcode',
        ),
    ]
