# Generated by Django 5.1.4 on 2025-01-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_conversation_participants_conversation_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
